import { createSlice } from "@reduxjs/toolkit";

// Create a Redux slice for adhanData with initial state set to null
const adhanDataSlice = createSlice({
  name: "adhanData", // Slice name, prefix for actions generated by this slice
  initialState: null, // Initial state of the adhanData slice is set to null
  reducers: {
    // Reducer function to handle the setAdhanData action
    setAdhanData: (state, action) => {
      return action.payload; // Update the state with the payload of the action
    },
  },
});

// Extract the action creator
export const { setAdhanData } = adhanDataSlice.actions;

// Export the reducer function
export default adhanDataSlice.reducer;
